version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "1000:1000"
    environment:
      - NEW_RELIC_LICENSE_KEY=YOUR_NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_APP_NAME=FlaskApp
    volumes:
      - .:/app
    restart: always
