name: Python CI + Docker + Render

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: franciscogb7/my-python-app
  PYTHON_VERSION: "3.13"

jobs:
  
  #  BUILD & TEST

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myproject 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_app.py


  # BUILD & PUSH DOCKER
  
  docker:
    name: Login to Docker Hub & Build Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./myproject         
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v1.0
            ${{ env.IMAGE_NAME }}:latest
  
  #  DEPLOY A RENDER
 
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: docker   # se ejecuta solo si docker terminó OK

    steps:
      - name: Trigger Render deploy hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
