name: Python CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./myproject

      - name: Run tests
        run: pytest test_app.py
        working-directory: ./myproject

      - name: Run linter (flake8)
        run: pip install flake8 && flake8 .
        working-directory: ./myproject

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./myproject
          file: ./myproject/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest